# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/37e406e9-e846-4ee9-b7b5-34d6900c5e09";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/390A-819F";
      fsType = "vfat";
    };

  swapDevices = [ ];

  fileSystems."/mnt/windows" =
	{ device = "/dev/disk/by-uuid/C64A1CD24A1CC0DB";
	  options = [ "rw" ];
	  fsType = "ntfs";
	};

  fileSystems."/mnt/stuff" =
	{ device = "/dev/disk/by-uuid/c7fd2de0-52c1-43d6-9a42-c4ac889a68b4";
	options = [ "rw" ];
	fsType = "ext4";
	};


 # NVIDIA

 environment.systemPackages = with pkgs; [
	 cudaPackages.cudatoolkit
 ];


 environment.sessionVariables = {
	WLR_NO_HARDWARE_CURSORS = "1";
	NIXOS_OZONE_WL = "1";

 };

 services.xserver.videoDrivers = [ "nvidia" ];

 hardware.nvidia = {
	modesetting.enable = true;
	powerManagement.enable = false;
	powerManagement.finegrained = false;
	open = false;
	nvidiaSettings = true;
	package = config.boot.kernelPackages.nvidiaPackages.latest;

 };

    # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
