format = """
$username\
$hostname\
$directory\
$git_status\
$git_branch\
$cmd_duration $jobs $time\
$c\
$dotnet\
$kotlin\
$java\
$lua\
$rust\
$nix_shell\
$sudo\
$battery\
$line_break\
$character"""
[character]
success_symbol = '🌸'

[fill]
symbol = " "

[hostname]
ssh_only = false

[username]
style_user = 'white bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[git_branch]
symbol = '🌱 '
