# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  inputs,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot = {
    loader = {
      efi.canTouchEfiVariables = true;
      grub = {
        enable = true;
        devices = [ "nodev" ];
        efiSupport = true;
        useOSProber = true;
      };
    };
    plymouth = {
      enable = false;
      themePackages = [ pkgs.mikuPlymouth ];
      theme = "MikuPlymouth";
    };
    kernelParams = [
      "intel_iommu=on"
      "xe.enable_dc=0"
      "xe.enable_fbc=0"
      "xe.max_vfs=7"
      "xe.force_probe=7d55"
      "i915.force_probe=!7d55"
      "quiet"
      "loglevel=3"
      "pcie_aspm=off"
      "intel_idle.max_cstate=2"
      "ahci.mobile_lpm_policy=1"
      "vfio-pci.ids=10de:25ac,10de:2291"
    ];
    kernelPackages = pkgs.linuxKernel.packages.linux_7_0;
    initrd.availableKernelModules = [
      "xhci_pci"
      "ahci"
      "usb_storage"
      "usbhid"
      "sd_mod"
      "rtsx_pci_sdmmc"
      "nvme"
      "vmd"
      "thunderbolt"
      "sdhci_pci"
      "vfio"
      "vfio_pci"
      "vfio_iommu_type1"
      "xe"
    ];
    initrd.kernelModules = [ "xe" ];
    kernelModules = [ "kvm-intel" ];
    tmp.cleanOnBoot = true;
    resumeDevice = "/dev/disk/by-uuid/260d9060-150c-40e3-9e8c-46f26a74461e";
  };
  powerManagement = {
    enable = true;
  };
  #services.logind.settings.Login.HandleLidSwitch = "ignore";
  hardware = {
    graphics = {
      enable = true;
      enable32Bit = true;
      extraPackages = with pkgs; [
        #vpl-gpu-rt
        intel-media-driver
      ];
      extraPackages32 = with pkgs.pkgsi686Linux; [ intel-vaapi-driver ];
    };
    nvidia = {
      modesetting.enable = true;
      open = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      #dynamicBoost.enable = true;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        intelBusId = "PCI:0:2:0";
        nvidiaBusId = "PCI:1:0:0";
      };
      package = config.boot.kernelPackages.nvidiaPackages.latest;
    };
    i2c.enable = true;
    bluetooth.enable = true;
  };
  services.xserver.videoDrivers = [
    "xe"
    "nvidia"
  ];
  services.thermald.enable = true;
  services.tlp = {
    enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

      CPU_ENERGY_PERF_POLICY_ON_BAT = "powersave";
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";

      START_CHARGE_THRESH_BAT0 = 40; # 40 and bellow it starts to charge
      STOP_CHARGE_THRESH_BAT0 = 80; # 80 and above it stops charging
    };
  };
  # Sound

  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
    jack.enable = true;
    wireplumber.enable = true;
    extraConfig.pipewire."92-low-latency" = {
      context.properties = {
        default.clock.rate = 48000;
        default.clock.quantum = 32;
        default.clock.min-quantum = 32;
        default.clock.max-quantum = 32;
      };
    };
  };
  services.btrfs.autoScrub = {
    enable = true;
    interval = "weekly";
  };
  networking.hostName = "lily"; # Define your hostname.

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/5f244270-0d6a-429a-b143-2c3a5a9241ab";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "compress=zstd"
    ];
  };

  boot.initrd.luks.devices."luks-260d9060-150c-40e3-9e8c-46f26a74461e".device =
    "/dev/disk/by-uuid/260d9060-150c-40e3-9e8c-46f26a74461e";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/DE0C-3221";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/dffca74a-cd48-40be-beb3-f48f1dafe776";
    fsType = "btrfs";
    options = [ "compress=zstd" ];

  };

  boot.initrd.luks.devices."luks-1868ff39-f1b7-4cc5-9624-58872c6e7d4f".device =
    "/dev/disk/by-uuid/1868ff39-f1b7-4cc5-9624-58872c6e7d4f";

  fileSystems."/home/kerojam/Windows" = {
    device = "/dev/disk/by-uuid/B616C4F716C4B99F";
    fsType = "ntfs";
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
